model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 128


data_params:
  data_path: "/Users/delshadkanjo/Projects/Bachelorprojekt/gesunddaten"
  train_batch_size: 32
  val_batch_size:  32
  patch_size: 32
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 25

logging_params:
  save_dir: "/Users/delshadkanjo/Projects/Bachelorprojekt/gesunddaten"
  name: "VanillaVAE"
  
